[project]
name = "income-classification-capstone"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.2",
    "matplotlib>=3.11.1",
    "numpy<2",
    "pandas>=2.3.3",
    "scikit-learn==1.1.3",
    "seaborn>=0.13.2",
    "tensorflow>=2.18.1",
]
